export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

export default function Contact() {
  return (
    <div className=" mt-[200px] mb-10">
      <p className=" font-bold text-center uppercase text-3xl">Contact</p>
    </div>
  );
}
