export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

export default function About() {
  return (
    <div className=" mt-[200px] mb-10">
      <p className=" font-bold text-center uppercase text-3xl">About</p>
    </div>
  );
}
