import FooterHome from "./components/FooterHome";
import HeroNav from "./components/HeroNav";
import "./globals.css";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        <HeroNav />
        {children}
        <FooterHome />
      </body>
    </html>
  );
}
