import FooterHome from "./components/FooterHome";
import HeroNav from "./components/HeroNav";
import HomeNav from "./components/HomeNav";
// import HeroSection from "./components/HeroSection_3"

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <HomeNav />
    </>
  );
}
