export const metadata = {
    title: 'Login',
    description: 'Generated by create next app',
  }
  
  export default function Login() {
    return (
      <div className=" mt-[200px]">
        <p className=" font-bold text-center uppercase text-3xl">Login</p>
      </div>
    )
  }
  