export const metadata = {
    title: 'Sign up',
    description: 'Generated by create next app',
  }
  
  export default function Signup() {
    return (
      <div className=" mt-[200px] mb-10">
      <p className=" font-bold text-center uppercase text-3xl">Signup</p>
    </div>
    )
  }
  